Fix checked flags not being updated in some cases
bernabe9/redux-react-native-session pull request #1
Opened 2019-05-13 22:34 UTC by mato2593

Those cases include when there is a session but there isn't a user, and when deleting the session and user.

2019-05-14 15:12 UTC, bernabe9 requested changes

2019-05-14 15:12 UTC, bernabe9 commented on src/immutableReducer.js
> +        sessionChecked: false
why this flag is changed to `false`? It should be changed to `true`. 

Since we use an async storage, the `sessionChecked` flag is useful to confirm if the library already read the storage.

2019-05-14 15:12 UTC, bernabe9 commented on src/immutableReducer.js
> +        userChecked: false
same here

2019-05-14 16:30 UTC, mato2593 commented on src/immutableReducer.js
> +        userChecked: false
This action is only being called in `deleteUser`. I added this because I think the `userChecked` flag should be reseted once you delete the user. If you don't reset `userChecked`, it becomes useless after a sign out because it will always be true.

2019-05-14 16:32 UTC, mato2593 commented on src/immutableReducer.js
> +        sessionChecked: false
I just saw that this action is being called in one more place other than `deleteSession`, so let me check how I can do this. But I'm applying the same as in the other comment

2019-05-20 13:16 UTC, bernabe9 commented on src/immutableReducer.js
> +        userChecked: false
Maybe you're misunderstanding the purpose of these flags. They are not useless after a sign out, the `userChecked` and `sessionChecked` flags indicate that the app already read the storage and the redux store is in sync with the storage (even if it doesn't have any user or session).

2019-05-20 13:17 UTC, bernabe9 commented on src/immutableReducer.js
> +        userChecked: false
Can you explain me what user case you want to cover with this change? Maybe we can add another flag

2019-07-12 04:19 UTC, closed without merging